kippnorcal/google_classroom

- main.py
`if_exists="replace"` fixed the insertion issue.
> PROJ-1794 Truncate and replace for all table insertions

- Pipfile
- README.md
- api.py
- config.py
- main.py
- timer.py
@susanxiong You can use this branch to work with.
> Refactor api

- README.md
Updates the README to help clarify some questions for someone coming to this repository fresh.
- Fixes formatting/spacing to match Prettier / README best practices.
- Adds clarifying details for variables.
- Adds missing steps that were causing errors.
> Update README to clarify on fresh installations

- .gitignore
- Dockerfile
- api.py
- main.py
Adds a number of safety checks in order to get this library to work on my machine from a fresh start and with sparely populated data in Google Classroom. These include issues where there is no organizational unit id, no guardians, etc.
Also fixes some errant bugs that were causing problems for me:
- An installation issue caused by Docker not using the right version of Python
- A timezone issue where Google was throwing an HttpError when the data requested wasn't far enough back in the past.
- A table reference issue where a schema appears to have been hardcoded (@dchess it seems to work for me without a schema at all, but can you confirm locally that the SELECT works without the `custom.` prefix?)
Resolves #15
> Adds safety measures based on sparse data and a fresh install

- .gitignore
- api.py
- main.py
- timer.py
Depends on `add_config_options`
This branch makes a number of substantial changes in the name of streaming data directly to the database. This is an admittedly large set of changes, so I welcome a close look, lots of feedback, and good testing before we merge it (or decide on a different approach).
Changes include:
- Moving basically all of the logic for fetching and filtering into `api.py`.
- Consolidating the different get functions into a single function that calls out prefiltering and postfiltering in subclassed functions as needed.
- Making explicit some assumptions on table names and request keys.
- Consolidating the `to_json`, `to_df`, `get`, and `get_by_course` functions into a single larger process so that data can be written as it comes in directly to the DB.
- Adding some …
> Adds data directly to DB as it comes in

- README.md
- config.py
- mailer.py
- main.py
Adds a configurable email notification for success/error reporting and attaches the log file output to the message.
Fixes #19
> Add notifications

- api.py
Resolves bug causing submissions to loop on multi-page requests. Also adds additional columns for data conversion to prevent SQL insertion errors.
Fixes #34
> Fix duplication error from submissions endpoint

- README.md
- api.py
- config.py
- main.py
Depends on #43 
Fixes #39, #40 
Parses the separate coursework dueDate and dueTime columns into a single date column. This should fix a bug where having no dueDate in the first batch of coursework led to a column with an incorrect data type.
> Parse coursework dates into one column

- api.py
Fixes #37 
Moves the retry logic to each individual batch request itself, and doesn't run it when in debug mode.
> Move Retry Logic To Batch Request

- api.py
- main.py
Fixes #32 
Adds organizational unit name, description, and path to the OrgUnit table.
> Add org unit name to db

- test_responses.py
Fixes an org unit test that I hadn't checked when merging the prior org unit change to add more columns.
> Fixes Org Unit Test

- api.py
Now that we have optimized the speed of requests, we are running up against user quota limits (600 requests / minute) on the Google Classroom API. This PR adds retry logic so that it snoozes for 20 seconds and then retries the requests. A few notes:
- It uses 20 seconds rather than a full 60 because the quota is a rolling 60 second window, so all that needs to happen is for some requests to fall out the back of that window.
- It rewrites the batching logic so that there is a stack and it is always just taking the top X requests off the stack. This has the benefit of also not waiting for all pages of one batch to finish before starting on the next batch, and instead can page through multiple batches together.
> Adds retry logic for quota limits

- test_response_class.py
- test_responses.py
- tests.py
Fixes #67
Adds tests for coursework and submissions, as well as splitting the test json and test classes into separate files to keep it more manageable.
> Add tests for coursework and submissions

- .github/workflows/pythonapp.yml
Creates an action for running automated linting and testing.
I haven't found a way to actually test this, so I'm not sure if it works yet.
> Create Action For Running Automated Tests

- README.md
- api.py
- config.py
- main.py
Wrote the code to add meet data and tested on my domain.  Working fine for me.
> Add Meet Data

- api.py
- config.py
- test_response_class.py
- test_responses.py
- tests.py
Adds two tests for student usage, checking that it generally functions and that the date window works.
> Add Tests For Student Usage

- .flake8
- .github/workflows/pythonapp.yml
- Pipfile
- api.py
- mailer.py
- main.py
Adds flake8 to the automated checks to catch a few things that black does not, and fixes the problems it raises — mostly unused imports and some line length issues.
> Adds Flake8 to checks

- .github/workflows/pythonapp.yml
- api.py
- config.py
- main.py
- test_all.py
- tests/mock_response.py
- tests/responses.py
Depends on #75
Does a variety of small code cleanup, including:
- Cleans up the DB Generator.
- Ports the rename logic from the BigQuery change here.
- Removes the duplicate Aliases call.
- Removes self-explanatory subclass comments
- Moves the auxiliary test files to their own folder (the actual tests file needs to stay in the root folder unless or until we convert this project into a package so that tests can import it correctly).
> Various Code Cleanup

- README.md
- api.py
- boot.sh
- test_all.py
- tests/mock_response.py
- tests/responses.py
Adds a test for the Meet endpoint. Also converts the date column to a date format in pandas.
> Add Test For Meet Endpoint

- google_classroom/endpoints/base.py
Improvement on #114 and #115 
In case of an upload error as seen in above issues, this PR upload each row one-by-one so that the bad row can be identified and the good data will still be uploaded.
I am unable to reproduce the errors mentioned, but this will hopefully help identify what kind of bad data is happening so that I can reproduce it later.
> In case of upload error, upload one-by-one to identify bad data

- .github/workflows/pythonapp.yml
- google_classroom/endpoints/base.py
- google_classroom/endpoints/course.py
Let's see if this resolves the issue with black.
> Install black v20.8 explicitly

- google_classroom/endpoints/base.py
Attempts to fix #120 
I'm hoping that by adding a retry attempt for the db write step that any encountered deadlocks will be freed up by the time the job retries.
> Deadlock retry
