- Pipfile
- README.md
- config.py
- main.py
Depends on `cleanup_api_calls`
Adds a configuration file that helps take care of selecting the DB, as well as taking in args so that the Dockerfile doesn't need to be edited every time you want to run something different.
NOTE: There was already a `config.py` file in the repo, but I couldn't find where it was used anywhere. I just deleted it entirely, but we can rename it to something else if someone is planning to use it.
I originally had the DB hang off the config object itself, but when that happens the initial import creates all of the DBs and causes errors. Still thinking if there's a nice way to encapsulate the DB generator so that `main.py` doesn't need to know about it at all.
Fixes #16, #20
> Add configuration options to abstract away DB and Args

- api.py
Fixes a bug where the org unit id wasn't being properly returned because the dataframe append was pivoting the result data.
This is a quick fix, but perhaps not the most elegant. An alternative solution may be ensuring that the OrgUnit filtering creates a format where the append functionality works as intended, but this change should at least unbreak the library so that it can continue to be used.
> Fixes Org Unit Pull

- api.py
- main.py
Changes the student usage pull so that it pulls from the last available today until today. This means that the data becomes idempotent (it can be run as frequently as you want without duplicating data) as well as not needing to be run every day to capture data.
Functionality includes:
- Deletes the last day in the database when available, because it may not be complete data. An alternative solution here would be to keep track of whether data is partial, but that would require parsing warnings from the JSON return and could be less reliable.
- If no data is available, it will start from the start of the school year. For fresh starts, that means it might take a few minutes to run. If we think there's a need, this date could also be a separate configuration date instead. This shouldn't have …
> Get All Student Usage From Last Updated Until Today

- Dockerfile
- Pipfile
- README.md
- api.py
- boot.sh
- config.py
- main.py
- test_responses.py
- tests.py
Depends on #33 
Fixes #14
This branch adds some basic testing using pytest. A few notes on changes:
- I went with creating a mock object rather than spoofing API calls since it felt more straightforward and are generally not concerned with the behavior of Google's library.
- There are many, many things that have not been tested. We can add to this over time, but this should give us enough safety to feel more comfortable with major changes like batch / parallel work.
- There are some "hacks" in the testing. Notably, I use the response and the endpoint.columns lists to check whether the database has been written to correctly. I also split the calls by course_id very arbitrarily, and only allow two class_ids right now. Ideally we can eventually make this more explicit, but this was done for …
> Add Initial Testing

- README.md
- api.py
- config.py
- main.py
- test_responses.py
- tests.py
Depends on #35 
Fixes #17
Test Plan: All local tests pass, manually verified that a run of main.py produces seemingly correct data into the DB.
This diff adds batch calling. It's a fairly substantial rewrite of the API, but the component changes are:
- Pushing params into the `request_data()` function so that they are more stateless and can be queued in a batch request.
- Pushing sql and config params into the initialize function so it is easily accessible everywhere and doesn't need to be passed as a param so much.
- Accumulating all of the batch requests and sending them off all at once to a batch object.
- Grouping those batches and adding params for batch size (by query) and page size, with defaults based on our own optimization.
- Handling those batches as they come in through the …
> Adds Batch Calling

- README.md
- config.py
- main.py
Depends on #38 
This PR moves authorization from Oauth2 to service accounts. We believe this will be more straightforward for other schools to use, as well as eliminating a step in the installation requiring locally running the script.
Explanations for how to get this functioning should be contained within the README — if it isn't clear, we should update that.
> Move Authorization To Service Accounts

- api.py
- main.py
Fixes #41
Instead of deleting the last day of data and rerunning it, this now detects partial data issues and doesn't load them at all. This is because there can actually be multiple days of partial data.
Also added a parameter filter to the usage report, which dramatically speeds up the request.
Note that it only does this if the partial data warning is for Google classroom — there are times where the partial data is only for other applications, and that is ok.
For testing / migration, make sure to manually delete any days with partial data first.
> Ignore partial data in usage report

- README.md
- config.py
Fixes #42 
Adds a `--all` flag for easily calling all of the endpoints. There's a lot more complexity to detecting if none of the flags have been used, so it is worth talking over the approach there if we want to go down that path(do we do it just for args or for the .env file, and is it more clear to have an opt-out rather than opt-in if we do that).
> Add a flag for pulling all data

- api.py
This fixes an error where an empty description causes the pandas `reindex` function to create a `float64` column for description, which then errors when a string is added to it. Instead, it just converts all columns to the `object` type (before later converting relevant points to the date type). The object dtype is capable of handling ints, floats, and strings.
This is something of a temporary fix, as the long-term solution if data types matter is to enumerate exactly which data type each column should be.
> Fix Pandas -> DB Type Error in Coursework

- main.py
Fixes #68 
Fixes a bug where having an empty usage table led to a TypeError trying to add a timedelta to a null date. This checks for the null date first.
> Fix Bug Caused By Empty Usage Table

- README.md
- api.py
- config.py
- main.py
- test_responses.py
Fixes #64
Improves performance by moving as much logic as possible out of the callback and into the batching, including record processing and file/DB writes. With the longest endpoint (Student Submissions), this improved performance from 31 minutes to 9 minutes.
With this change, further optimization of batch size may also increase performance. In one test, I increased batch size to 300 and was able to run at 8.5 minutes.
> Improve performance by moving logic out of callback

- api.py
- tests/responses.py
Fixes #81 
Adds a late column to student submissions. Responses only include the bool when it is true, so the code manually inserts False in other cases.
Tested manually and with the test suite.
> Adds late column to student submissions

- google_classroom/api.py
- tests/mock_response.py
- tests/responses.py
- tests/test_all.py
Fixes #92 
Depends on #84 
Adds a course ID to Aliases, as well as any other future endpoint that might need it.
This also replaces a hacky implementation of execution by course ID in the testing object so that it actually filters the response object by the course ID in the response. It is not used in the case of aliases because the response doesn't contain course IDs, but it was called to attention when I added the API code and discovered the course IDs weren't matching up between request and solution.
> Adds Course ID to Aliases

- google_classroom/api.py
- google_classroom/main.py
Fixes #95 
Removes request param filtering on ACTIVE courseState and adds query filter to course_ids for ACTIVE courses. This way we have a record of which courses are archived but are not making requests to the coursework, submissions, etc endpoints for non-active courses.
> Course states

- google_classroom/endpoints/course.py
- google_classroom/main.py
Fixes a bug where the Invitation pull would run twice.
Also fixes a bug where only turning on PULL_MEET wouldn't get the list of courses.
> Remove second run of Invitation

- google_classroom/endpoints/base.py
- google_classroom/endpoints/course.py
- google_classroom/main.py
- google_classroom/sync_files/courses_sample.csv
- tests/sync_data.py
- tests/test_all.py
Depends on #96
Fixes #85 
Adds "diffing" logic to check the differences between source data and the database, and returns data that should either be deleted/archived or created.
Tests pass and should cover the corner cases I can think of so far.
A few notes for future cleanup:
- Right now the CourseAliases object gets created from within the Base, which is not a great pattern. Eventually I'd like to refactor this so that a Controller object creates all of the endpoints and can then pass in the Aliases information that is needed.
- The clearing of databases in the test suite should happen in a teardown() function rather than in the test itself, but I haven't yet found a good way to clear the whole database. Until I do that, just dropping the table from the associated endpoint seems to work …
> Check differences between source data and the database

- run_tests.sh
Fixes #106 
Fixes an issue where the Github Action was not properly failing when tests failed. This propagates the test failure to the action itself.
Note that the result has to be stored after the first docker-compose call, because otherwise $? will be overwritten by the results of the second call (which should always be successful).
> Ensure Github Action check properly fails when the tests fail

- google_classroom/endpoints/course.py
- tests/responses.py
Fixes #113 
Adds the Calendar ID to the Courses Endpoint. Because Courses is dropped every time, no migration is necessary.
> Adds Calendar Id to Courses Endpoint

- google_classroom/endpoints/announcement.py
- google_classroom/endpoints/base.py
- google_classroom/endpoints/student_usage.py
Fixes a few issues I'm coming across from various Google Classroom data:
- Having the character "\x00" in announcements, which is a NULL character and has problems saving to a DB.
- Missing a date in a student usage record, which will now default to 1970 (what Google uses when someone hasn't logged in yet).
> Fixes for Google Classroom missing data

- google_classroom/endpoints/base.py
- google_classroom/endpoints/course.py
- google_classroom/endpoints/meet.py
- google_classroom/main.py
Fixes #100 
Converts Meet pulls so that it only pulls the latest data.
> Convert meet data to incremental additions
